import fs from 'node:fs';
import path from 'node:path';
import { stripTypeScriptTypes } from 'node:module';
import { fileURLToPath } from 'node:url';

const core = path.dirname(fileURLToPath(import.meta.url));
const src = path.join(core, 'src');
const dist = path.join(core, 'dist');
const HEADER = '// Generated by core/build.ts from core/src. Do not edit; edit the .ts source and rerun the build.\n';
const ENTRIES: Record<string, string> = {
  'event.js': 'hook/event.ts',
  'launch.js': 'hook/launch.ts',
  'codex-notify.js': 'hook/codex-notify.ts',
  'mcp-shim.js': 'hook/mcp-shim.ts',
  'code-host.js': 'hook/code-host.ts',
  'metatrooper-browser.js': 'hook/browser-mcp.ts',
};

function localImports(code: string): string[] {
  return [...code.matchAll(/(?:from\s+|import\s*\(\s*)'(\.{1,2}\/[^']+\.ts)'/g)].map((m) => m[1]);
}

function collect(entry: string, seen = new Set<string>()): Set<string> {
  const abs = path.join(src, entry);
  if (seen.has(abs) || !fs.existsSync(abs)) return seen;
  seen.add(abs);
  for (const spec of localImports(fs.readFileSync(abs, 'utf8'))) collect(path.relative(src, path.resolve(path.dirname(abs), spec)), seen);
  return seen;
}

function outputs(): Map<string, string> {
  const files = new Map<string, string>();
  const modules = new Set<string>();
  for (const entry of Object.values(ENTRIES)) for (const m of collect(entry)) modules.add(m);
  for (const abs of modules) {
    const rel = path.relative(src, abs).replace(/\.ts$/, '.js');
    const js = stripTypeScriptTypes(fs.readFileSync(abs, 'utf8'), { mode: 'strip' })
      .replace(/((?:from\s+|import\s*\(\s*)'\.{1,2}\/[^']+)\.ts'/g, "$1.js'");
    files.set(path.join(dist, rel), HEADER + js);
  }
  for (const [out, entry] of Object.entries(ENTRIES)) {
    if (!fs.existsSync(path.join(src, entry))) continue;
    files.set(path.join(core, out), HEADER + `import './dist/${entry.replace(/\.ts$/, '.js')}';\n`);
  }
  return files;
}

const check = process.argv.includes('--check');
let stale = 0;
for (const [file, content] of outputs()) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`out of date: ${path.relative(core, file)}`);
    stale++;
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`wrote ${path.relative(core, file)}`);
  }
}
process.exit(check && stale ? 1 : 0);
