#!/usr/bin/env bash
# Run from projects/agent-harness after creating the GitHub repo. Nothing here runs automatically.
set -euo pipefail
for m in "M1 core loop" "M2 design and coding lanes" "M3 every other lane"; do
  gh api "repos/{owner}/{repo}/milestones" -f title="$m" >/dev/null || true
done
gh issue create --title "#1 Core service" --milestone "M1 core loop" --body-file "issues/01-core-service.md"
gh issue create --title "#3 Plugin system" --milestone "M1 core loop" --body-file "issues/03-plugin-system.md"
gh issue create --title "#2 Callrouter Plan A, in the callrouter repo, meeting its own criteria 1 to 8; then its `harness-plugin.json`" --milestone "M1 core loop" --body-file "issues/02-callrouter-plan-a-in-the-callrouter-repo-meeting-i.md"
gh issue create --title "#4 Pipeline runner" --milestone "M1 core loop" --body-file "issues/04-pipeline-runner.md"
gh issue create --title "#5 Electron workbench" --milestone "M1 core loop" --body-file "issues/05-electron-workbench.md"
gh issue create --title "#6 Live browser" --milestone "M1 core loop" --body-file "issues/06-live-browser.md"
gh issue create --title "#9 Two-engine review pipeline and view" --milestone "M1 core loop" --body-file "issues/09-two-engine-review-pipeline-and-view.md"
gh issue create --title "#10 Hand-back tray" --milestone "M1 core loop" --body-file "issues/10-hand-back-tray.md"
gh issue create --title "#11 Token meter and prices (reads `usage` from #1 and callrouter \"saved\")" --milestone "M1 core loop" --body-file "issues/11-token-meter-and-prices-reads-usage-from-1-and-call.md"
gh issue create --title "#31 Agent-native `harness` CLI and skill" --milestone "M1 core loop" --body-file "issues/31-agent-native-harness-cli-and-skill.md"
gh issue create --title "#13 Measurement tooling for the adoption gate" --milestone "M1 core loop" --body-file "issues/13-measurement-tooling-for-the-adoption-gate.md"
gh issue create --title "#7 Inspiration board and `agent-reach` plugin" --milestone "M2 design and coding lanes" --body-file "issues/07-inspiration-board-and-agent-reach-plugin.md"
gh issue create --title "#8 Variants grid" --milestone "M2 design and coding lanes" --body-file "issues/08-variants-grid.md"
gh issue create --title "#14 `github` and `deploy` plugins; `spec-to-pr`, `e2e-browser-qa`, `website-build`, `design-variants`" --milestone "M2 design and coding lanes" --body-file "issues/14-github-and-deploy-plugins-spec-to-pr-e2e-browser-q.md"
gh issue create --title "#23 `docs-and-release-notes`" --milestone "M2 design and coding lanes" --body-file "issues/23-docs-and-release-notes.md"
gh issue create --title "#25 `security` plugin and `security-review-and-upgrade`" --milestone "M2 design and coding lanes" --body-file "issues/25-security-plugin-and-security-review-and-upgrade.md"
gh issue create --title "#27 herdr host plugin" --milestone "M2 design and coding lanes" --body-file "issues/27-herdr-host-plugin.md"
gh issue create --title "#29 Usage limits and account switcher" --milestone "M2 design and coding lanes" --body-file "issues/29-usage-limits-and-account-switcher.md"
gh issue create --title "#30 Diff annotation and file drag" --milestone "M2 design and coding lanes" --body-file "issues/30-diff-annotation-and-file-drag.md"
gh issue create --title "#28 Signed packaging through SignPath Foundation (Electron now; Tauri in milestone 3)" --milestone "M2 design and coding lanes" --body-file "issues/28-signed-packaging-through-signpath-foundation-elect.md"
gh issue create --title "#15 `media` plugin and `footage-to-edit`" --milestone "M3 every other lane" --body-file "issues/15-media-plugin-and-footage-to-edit.md"
gh issue create --title "#16 `social-scheduler` plugin and `clips-to-scheduled-posts`" --milestone "M3 every other lane" --body-file "issues/16-social-scheduler-plugin-and-clips-to-scheduled-pos.md"
gh issue create --title "#17 `seo` plugin and `seo-audit-fix`" --milestone "M3 every other lane" --body-file "issues/17-seo-plugin-and-seo-audit-fix.md"
gh issue create --title "#18 `cite-check` plugin and `deep-research-cited`" --milestone "M3 every other lane" --body-file "issues/18-cite-check-plugin-and-deep-research-cited.md"
gh issue create --title "#19 `gmail` plugin, `prospect-list-to-drafts`, `inbox-triage-drafts`" --milestone "M3 every other lane" --body-file "issues/19-gmail-plugin-prospect-list-to-drafts-inbox-triage-.md"
gh issue create --title "#20 `data` plugin and `data-to-dashboard`" --milestone "M3 every other lane" --body-file "issues/20-data-plugin-and-data-to-dashboard.md"
gh issue create --title "#22 `docs-export` plugin and `study-notes-to-pdf`" --milestone "M3 every other lane" --body-file "issues/22-docs-export-plugin-and-study-notes-to-pdf.md"
gh issue create --title "#24 `desktop` plugin, handoff gate UI, `form-fill-batch`" --milestone "M3 every other lane" --body-file "issues/24-desktop-plugin-handoff-gate-ui-form-fill-batch.md"
gh issue create --title "#21 Template gallery (17 templates)" --milestone "M3 every other lane" --body-file "issues/21-template-gallery-17-templates.md"
gh issue create --title "#12 Tauri tray companion, signed through #28's pipeline" --milestone "M3 every other lane" --body-file "issues/12-tauri-tray-companion-signed-through-28-s-pipeline.md"
gh issue create --title "#26 Open-core seams" --milestone "M3 every other lane" --body-file "issues/26-open-core-seams.md"
